name: "Test and build bindings"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: valhalla-go
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
    - uses: actions/upload-artifact@v3
      with:
        name: libvalhalla-go
        path: result/lib/libvalhalla_go.so
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - name: Run go test unit
      run: |
        export LD_LIBRARY_PATH=result/lib/
        go test -v
